FROM w251/l4t-ml:r32.4.4-py3

RUN pip3 install facenet-pytorch

RUN git clone https://github.com/timesler/facenet-pytorch.git facenet_pytorch
#ADD facedetect.ipynb /facenet_pytorch/examples/
#ADD facedetect_cv2.ipynb /facenet_pytorch/examples/

RUN pip3 install paho-mqtt
