FROM w251/l4t-pytorch:r32.4.4-pth1.7-py3

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt update && apt install -y  libssl-dev

RUN apt update && apt install -y libffi-dev python3-pip curl unzip python3-tk libopencv-dev python3-opencv 
RUN pip3 install -U gsutil pyyaml tqdm cython torchvision   
RUN apt install -y python3-scipy python3-matplotlib python3-numpy
RUN pip3 install -U pip
RUN apt install -y vim
RUN pip3 install opencv-python

